/*
 *  Copyright (c) 2011, Franz Bettag <franz@bett.ag>
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * All advertising materials mentioning features or use of this software
 *       must display the following acknowledgement:
 *       This product includes software developed by the Bettag Systems UG
 *       and its contributors.
 *
 *  THIS SOFTWARE IS PROVIDED BY BETTAG SYSTEMS UG ''AS IS'' AND ANY
 *  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  DISCLAIMED. IN NO EVENT SHALL BETTAG SYSTEMS UG BE LIABLE FOR ANY
 *  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 *  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

package code
package model

import net.liftweb.mapper._
import net.liftweb.util._
import net.liftweb.common._
import java.util.Date

import java.util.regex.Pattern
import dispatch._
import scala.xml._

object Share extends Share with LongKeyedMetaMapper[Share] {
	override def dbTableName = "shares"
}

class Share extends LongKeyedMapper[Share] with IdPK {
	def getSingleton = Share

	object username extends MappedString(this, 255) {
		override def dbIndexed_? = true
		override def dbNotNull_? = true
	}

	object remoteHost extends MappedString(this, 255) {
		override def dbColumnName = "rem_host"
		override def dbNotNull_? = true
	}

	object ourResult extends MappedBoolean(this) {
		override def dbColumnName = "our_result"
		override def dbNotNull_? = true
		override def defaultValue = false
	}

	object upstreamResult extends MappedBoolean(this) {
		override def dbColumnName = "upstream_result"
		//override def dbNotNull_? = true
		//override def defaultValue = false
	}

	object reason extends MappedString(this, 255) {
//		override def dbNotNull_? = true
	}

	object solution extends MappedString(this, 1024) {
//		override def dbNotNull_? = true
	}

	object timestamp extends MappedDateTime(this) {
		override def dbNotNull_? = true
	}

	object source extends MappedString(this, 255) {
//		override def dbNotNull_? = true
	}

	object network extends MappedString(this, 20) {
		override def dbNotNull_? = true
		override def dbIndexed_? = true
	}

}


object WonShare extends WonShare with LongKeyedMetaMapper[WonShare] {
	override def dbTableName = "won_shares"
}

class WonShare extends LongKeyedMapper[WonShare] {
	def getSingleton = WonShare
	override def primaryKeyField = id

	object id extends MappedLongIndex(this) {
		override def dbAutogenerated_? = false
		override def writePermission_? = true
	}

	object blockNumber extends MappedLong(this) {
		override def dbIndexed_? = true
		override def dbNotNull_? = true
		override def defaultValue = 0L
	}

	object hash extends MappedString(this, 255)
	object txid extends MappedString(this, 255)

	object paid extends MappedBoolean(this) {
		override def dbIndexed_? = true
		override def dbNotNull_? = true
		override def defaultValue = false
	}

	object username extends MappedString(this, 255) {
		override def dbIndexed_? = true
		override def dbNotNull_? = true
	}

	object ourResult extends MappedBoolean(this) {
		override def dbColumnName = "our_result"
		override def dbNotNull_? = true
		override def defaultValue = false
	}

	object upstreamResult extends MappedBoolean(this) {
		override def dbColumnName = "upstream_result"
		//override def dbNotNull_? = true
		//override def defaultValue = false
	}

	object reason extends MappedString(this, 255) {
//		override def dbNotNull_? = true
	}

	object solution extends MappedString(this, 1024) {
//		override def dbNotNull_? = true
	}

	object timestamp extends MappedDateTime(this) {
		override def dbNotNull_? = true
	}

	object source extends MappedString(this, 255) {
//		override def dbNotNull_? = true
	}

	object network extends MappedString(this, 20) {
		override def dbNotNull_? = true
		override def dbIndexed_? = true
	}

	object category extends MappedString(this, 20) {
		override def dbNotNull_? = true
		override def dbIndexed_? = true
	}

	object confirmations extends MappedLong(this) {
		override def defaultValue = 0L
	}

	object shares extends MappedLong(this) {
		override def dbNotNull_? = true
		override def defaultValue = 0L
	}

	object stales extends MappedLong(this) {
		override def dbNotNull_? = true
		override def defaultValue = 0L
	}

	def fetchInfo {
		if (this.blockNumber.is != 0L || this.txid.is == "" || this.category.is == "orphan") return

		val h = new Http
		val r = (if (this.network.is == "bitcoin") :/("blockexplorer.com") else :/("150.214.61.49", 2750)) / "tx" / this.txid.is
		val ignore = r >|

		val output = h(r >- { str => str }).toString
		val m = Pattern.compile("<a [^>]*href=\".*/block/([^\"]+)\"[^>]*>(?:SolidCoin|Namecoin|block) ([0-9]+)</a>").matcher(output)
		if (m.find) try { this.blockNumber(m.group(2).toLong).hash(m.group(1)).save } catch { case _ => }
		h.shutdown
	}

	def blockLink: NodeSeq = {
		if (this.category.toString == "orphan") return <a href="https://en.bitcoin.it/wiki/Block_chain" target="_blank">invalid</a>
		if (this.blockNumber.is == 0L || this.hash.is == "") return Text("tbd")
		
		val url = if (this.network.is == "bitcoin") "blockexplorer.com" else "blockexplorer.sytes.net"
		<a href={"http://%s/block/%s".format(url, this.hash.is)} target="_blank">{this.blockNumber.toString}</a>
	}

}
